name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: windows-latest
    steps: 
      - name: greeting
        run: echo "Hello World!"
      - name: good bye
        run: |
              echo "good bye friends"
              echo "iam saying good bye!"
    
